#pragma once

/// @file event_types.h
/// @brief Core event type system, identifiers, enums, and flag bitmasks.
///
/// Part of UME Milestone M2 (Event System & Journal).

#include "ume/types.h"

#include <cstdint>
#include <string_view>
#include <type_traits>

namespace ume::event {

/// @brief Strongly-typed identifier for Events.
struct EventId {
    uint64_t raw_value{0};

    constexpr EventId() noexcept = default;
    explicit constexpr EventId(uint64_t val) noexcept : raw_value(val) {}

    [[nodiscard]] constexpr bool is_valid() const noexcept { return raw_value != 0; }
    [[nodiscard]] constexpr uint64_t to_raw() const noexcept { return raw_value; }

    constexpr bool operator==(const EventId& other) const noexcept = default;
    constexpr bool operator!=(const EventId& other) const noexcept = default;
};

static inline constexpr EventId kNullEventId{0};

/// @brief Event Categories grouping major subsystem events.
enum class EventCategory : uint8_t {
    kUnknown = 0,
    kMemoryObject = 1,   ///< Object creation, destruction, resize, allocation
    kTierMigration = 2,  ///< Object movement between memory tiers
    kAccessPattern = 3,  ///< Page faults, access frequency, access samples
    kSystemTopology = 4, ///< Topology discovery, tier availability, power state
    kPrediction = 5,     ///< Prediction engine model inferences & recommendations
    kAdvisor = 6,        ///< Policy engine advice & decision directives
    kPlugin = 7          ///< User-defined plugin telemetry & custom events
};

/// @brief Specific Event Types under each category.
enum class EventType : uint16_t {
    kUnknown = 0x0000,

    // ── Memory Object Events (0x01xx) ──
    kObjectCreated = 0x0101,
    kObjectDestroyed = 0x0102,
    kObjectResized = 0x0103,
    kObjectBindTier = 0x0104,
    kObjectUnbindTier = 0x0105,

    // ── Tier Migration Events (0x02xx) ──
    kMigrationRequested = 0x0201,
    kMigrationStarted = 0x0202,
    kMigrationCompleted = 0x0203,
    kMigrationFailed = 0x0204,
    kMigrationCancelled = 0x0205,

    // ── Access Pattern Events (0x03xx) ──
    kAccessSample = 0x0301,
    kPageFault = 0x0302,
    kWorkingSetUpdated = 0x0303,
    kHotnessChanged = 0x0304,

    // ── System Topology Events (0x04xx) ──
    kTierRegistered = 0x0401,
    kTierUnregistered = 0x0402,
    kTierPressureHigh = 0x0403,
    kTierPressureNormal = 0x0404,
    kBandwidthThrottled = 0x0405,

    // ── Prediction & Policy Events (0x05xx) ──
    kPredictionGenerated = 0x0501,
    kPolicyDecisionMade = 0x0502,
    kCostModelUpdated = 0x0503,

    // ── Plugin & Custom Events (0x06xx) ──
    kPluginCustom = 0x0601
};

/// @brief Event Priority for ordering & journal flushing queues.
enum class EventPriority : uint8_t {
    kLow = 0,     ///< Non-critical background telemetry (e.g. access samples)
    kNormal = 1,  ///< Standard operation events (allocations, predictions)
    kHigh = 2,    ///< Time-sensitive events (migrations, working set changes)
    kCritical = 3 ///< Immediate processing needed (pressure high, system alerts)
};

/// @brief Bitmask flags specifying event handling directives.
enum class EventFlags : uint32_t {
    kNone = 0,
    kSynchronous = 1 << 0, ///< Event requiring synchronous handling
    kJournaled = 1 << 1,   ///< Must be persisted to append-only journal file
    kReplayed = 1 << 2,    ///< Event emitted during crash recovery / replay
    kCompressed = 1 << 3,  ///< Payload is compressed
    kSynthetic = 1 << 4    ///< Generated by prediction/simulation, not hardware
};

[[nodiscard]] constexpr EventFlags operator|(EventFlags a, EventFlags b) noexcept {
    return static_cast<EventFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}

[[nodiscard]] constexpr EventFlags operator&(EventFlags a, EventFlags b) noexcept {
    return static_cast<EventFlags>(static_cast<uint32_t>(a) & static_cast<uint32_t>(b));
}

[[nodiscard]] constexpr EventFlags operator~(EventFlags a) noexcept {
    return static_cast<EventFlags>(~static_cast<uint32_t>(a));
}

[[nodiscard]] constexpr bool has_flag(EventFlags flags, EventFlags flag) noexcept {
    return (flags & flag) == flag;
}

/// @brief Human-readable category string representation.
[[nodiscard]] constexpr std::string_view category_name(EventCategory cat) noexcept {
    switch (cat) {
        case EventCategory::kMemoryObject:
            return "MemoryObject";
        case EventCategory::kTierMigration:
            return "TierMigration";
        case EventCategory::kAccessPattern:
            return "AccessPattern";
        case EventCategory::kSystemTopology:
            return "SystemTopology";
        case EventCategory::kPrediction:
            return "Prediction";
        case EventCategory::kAdvisor:
            return "Advisor";
        case EventCategory::kPlugin:
            return "Plugin";
        default:
            return "Unknown";
    }
}

/// @brief Human-readable event type string representation.
[[nodiscard]] constexpr std::string_view type_name(EventType type) noexcept {
    switch (type) {
        case EventType::kObjectCreated:
            return "ObjectCreated";
        case EventType::kObjectDestroyed:
            return "ObjectDestroyed";
        case EventType::kObjectResized:
            return "ObjectResized";
        case EventType::kObjectBindTier:
            return "ObjectBindTier";
        case EventType::kObjectUnbindTier:
            return "ObjectUnbindTier";
        case EventType::kMigrationRequested:
            return "MigrationRequested";
        case EventType::kMigrationStarted:
            return "MigrationStarted";
        case EventType::kMigrationCompleted:
            return "MigrationCompleted";
        case EventType::kMigrationFailed:
            return "MigrationFailed";
        case EventType::kMigrationCancelled:
            return "MigrationCancelled";
        case EventType::kAccessSample:
            return "AccessSample";
        case EventType::kPageFault:
            return "PageFault";
        case EventType::kWorkingSetUpdated:
            return "WorkingSetUpdated";
        case EventType::kHotnessChanged:
            return "HotnessChanged";
        case EventType::kTierRegistered:
            return "TierRegistered";
        case EventType::kTierUnregistered:
            return "TierUnregistered";
        case EventType::kTierPressureHigh:
            return "TierPressureHigh";
        case EventType::kTierPressureNormal:
            return "TierPressureNormal";
        case EventType::kBandwidthThrottled:
            return "BandwidthThrottled";
        case EventType::kPredictionGenerated:
            return "PredictionGenerated";
        case EventType::kPolicyDecisionMade:
            return "PolicyDecisionMade";
        case EventType::kCostModelUpdated:
            return "CostModelUpdated";
        case EventType::kPluginCustom:
            return "PluginCustom";
        default:
            return "Unknown";
    }
}

} // namespace ume::event
