name: 'Static Analysis'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy-17 ninja-build cmake
          
      - name: Configure CMake
        run: >
          cmake -B build
          -G Ninja
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DUME_BUILD_TESTS=ON
          -DCMAKE_C_COMPILER=clang-17
          -DCMAKE_CXX_COMPILER=clang++-17

      - name: Run clang-tidy
        run: |
          find core -type f \( -name '*.cpp' \) | xargs -r clang-tidy-17 -p build --warnings-as-errors='*'
